steps:
  - name: "gcr.io/cloud-builders/docker"
    id: "build_latency_simulator"
    entrypoint: "bash"
    args:
      - "docker_build"
      - "${_REPO_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_IMAGE_NAME}:${_IMAGE_TAG}"
images:
  - "${_REPO_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_IMAGE_NAME}:${_IMAGE_TAG}"
tags: ["latency-simulator"]
options:
  logging: CLOUD_LOGGING_ONLY
