app.startup.latency.enabled=true
app.startup.latency.min=2
app.startup.latency.max=5

app.coldstart.spikeFactor=1

# properties for root endpoint: `/`
app.response.code._root_=200
app.response.latency.enabled._root_=true
app.response.latency.min._root_=1
app.response.latency.max._root_=3
app.response.latency.spikeFactor._root_=1

app.initialization.latency.enabled=true
app.initialization.latency.min=1
app.initialization.latency.max=3
app.initialization.latency.spikeFactor=1

app.web.requests.pendingLatency.max=300
app.web.requests.concurrency.min=10
app.web.requests.concurrency.max=80
